name: starter-ci

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12 # ${{ matrix.node-version }}

      - name: Install jest
        run: npm ci
      - name: Test
        run: npm test
